### ISSUE TITLE
Exchange Wallet!

### ISSUE THREAD

**Issue by biscrypto** [AX-NET/axnet_issue_tracker#2]
my ETH is stuck in order but didn't show that order!  username: Marc
![ax net](https://user-images.githubusercontent.com/45098158/48622484-3ef73a00-e9a7-11e8-8ab2-d64845cc7946.png)
![axnet1](https://user-images.githubusercontent.com/45098158/48622750-11f75700-e9a8-11e8-9e1a-64614ab7e4d6.png)
![axnet2](https://user-images.githubusercontent.com/45098158/48622822-49fe9a00-e9a8-11e8-9b24-813fea867541.png)

**Comment by superdev810** [comment]
Please try cancel order for now
@biscrypto

**Comment by biscrypto** [comment]
> Please try cancel order for now
> @biscrypto

 issue solved! thank you:-)
